export interface CareerTranslation {
  name?: string;
  tagline?: string;
  description?: string;
  specializations?: string[];
  projects?: string[];
  labs?: string[];
  /** Custom project-group nodes that aren't generated by the shared practice/career helpers. */
  projectGroups?: Record<string, { label?: string; projects?: string[] }>;
}

export interface ItemTranslation {
  /** Only set for concepts/certifications — real product/language names (React, Python, AWS) stay untranslated. */
  name?: string;
  description?: string;
  usedFor?: string[];
  learn?: string[];
  projects?: string[];
}
